### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by redthing1** [redthing1/irre-tools#3]

**Comment by xdrie** [comment]
<img width="303" alt="Screenshot 2021-05-07 at 3 42 56 PM" src="https://user-images.githubusercontent.com/54390138/117515438-2306fa80-af4b-11eb-9789-6cbc48c1f06d.png">
<img width="676" alt="Screenshot 2021-05-07 at 3 41 55 PM" src="https://user-images.githubusercontent.com/54390138/117515441-27331800-af4b-11eb-80e1-65ae89a8f17b.png">

**Comment by xdrie** [comment]
<img width="687" alt="Screenshot 2021-05-07 at 3 47 47 PM" src="https://user-images.githubusercontent.com/54390138/117515640-afb1b880-af4b-11eb-914c-5e0dd048bec0.png">
